services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
<<<<<<< HEAD:ProjectSourceCode/docker-compose.yaml
    working_dir: /repository
=======
    #user: 'node'
    working_dir: /Travel-Planner
    env_file: .env
>>>>>>> e79027c (started to add calendar.hbs):docker-compose.yaml
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/Travel-Planner
    command: 'npm start'
volumes:
  postgres-data: