services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ProjectSourceCode/src/init_data:/docker-entrypoint-initdb.d  #had to update path, to get into the createsql to create the tables
  web:
    image: node:lts
    #user: 'node'
    working_dir: /Travel-Planner #updated from just /repository
    env_file: .env
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/Travel-Planner
    command: 'npm start'
volumes:
  postgres-data: